name: Build

on: [push] # Enables manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    environment: github-pages
    
    steps:
    # Step 1: Check out the code
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    

    - name: ✅ Ready for Deployment
      run: echo "Deployment is ready for deployment!"

  deploy:
    runs-on: ubuntu-latest
    needs: build  # This ensures deploy job only runs if build job succeeds
    environment: production  # Specify your environment, if any

    steps:
      # Step 1: Download build artifacts from the build job
      - name: Download Build Artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-files

      # Step 2: Deploy to FTP server
      - name: 📂 Upload to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
          local-dir: ./build  # Directory containing downloaded build artifacts
          server-dir: /  # Target directory on your server

      # Step 3: Confirm deployment
      - name: ✅ Confirm Deployment
        run: echo "Deployment completed successfully!"